# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2NhOThmNjBhOGJkYzE3YmRkNzUwMGIyN2Q4NjM1YzA1NmQ4NzdlYTU4MzBmYWM2MTlkYzE3YzM2YjhkNTlmMTU0NmI3NjE0MjM4MjkyYWEyOThhYjlmNjI2ZTc1Mzc0MTJkZTZiMDJkYzdlZGE0NWNhNGIyYmJkOGFmNmEzYjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
