# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzRmNmVjNzk4MjliMGY4MmMxMjA2NzEzYjNmZjFhOTZkMTM0YTNjZmJiNGYxMjA2ZWI5ODg5NWY4MDVlYzNiODY2OGMxYTIwYWY5ZWRiNDlkNGZiOWRhODAyY2U5ZmViNjliOGVmZjhlOWM5NTczYjRjZmY5OTI5ZTE0MjViMWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
